- hosts: nodes
  become: true
  tasks:
    - name: Debug node provisioning
      debug:
        msg: "Node-specific provisioning would happen here."

    # Step 18: Generate Join Command
    - name: Generate join command on the controller
      shell: kubeadm token create --print-join-command
      delegate_to: "{{ groups['ctrl'][0] }}"
      run_once: true
      register: join_cmd
      retries: 5  # NOTE: Wait for the controller to be ready !!!!!!
      delay: 10

    # Step 19: Run Join Command
    - name: Join this worker to the Kubernetes cluster
      shell: "{{ join_cmd.stdout }} --ignore-preflight-errors=all"
      args:
        creates: /etc/kubernetes/kubelet.conf
