- hosts: nodes
  become: true
  tasks:
    - name: Debug node provisioning
      debug:
        msg: "Node-specific provisioning would happen here."

    - name: Generate join command on the controller
      shell: kubeadm token create --print-join-command
      delegate_to: "{{ groups['ctrl'][0] }}"
      become_user: vagrant
      run_once: true
      register: join_cmd

    - name: Join this worker to the Kubernetes cluster
      shell: "{{ join_cmd.stdout }} --ignore-preflight-errors=all"
      args:
        creates: /etc/kubernetes/kubelet.conf
