{
 "title": "Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Requests per Second",
   "type": "gauge",
   "description": "Rate of requests per second",
   "gridPos": { "h": 8, "w": 8, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(sentiment_predictions_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Positive Sentiments Ratio",
   "type": "gauge",
   "description": "Amount of total sentiments that are positive",
   "gridPos": { "h": 8, "w": 8, "x": 14, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(sentiment_positive_ratio)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Prediction Latency (50th Percentile) ",
   "type": "timeseries",
   "description": "Observe median latency to understand typical latency experience for users. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, rate(sentiment_prediction_latency_seconds_bucket[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Sentiment Predictions",
   "type": "timeseries",
   "description": "Tracks the total number of sentiment predictions made. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (sentiment) (sentiment_predictions_total)",
     "legendFormat": "{{sentiment}}"
    }
   ]
  }
 ]
}