{{- if .Values.configMap.create }} 
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-configmap
data:
  {{- range $key, $value := .Values.configMap.data }}
  {{ $key }}: "{{ $value }}"
  {{- end }}
{{- end }}
