apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-{{ .Values.appFrontend.name }}-vs
spec:
  gateways:
    - {{ .Release.Name }}-gateway 
  hosts:
    - "*"
  http:
    # Sticky routing when `user` header is present and matches 
    - name: "canary-sticky"
      match:
        - headers:
            user:
              regex: "^(10|20|30|40|50|60|70|80|90|100)$"
          uri:
            prefix: /
      route:
        - destination:
            host: {{ .Release.Name }}-{{ .Values.appFrontend.name }}
            subset: v2

    # Sticky routing fallback for other `user` values 
    - name: "sticky-default"
      match:
        - headers:
            user:
              regex: ".*"
          uri:
            prefix: /
      route:
        - destination:
            host: {{ .Release.Name }}-{{ .Values.appFrontend.name }}
            subset: v1

    # Weighted routing when `user` header is missing 
    - name: "weighted-default"
      match:
        - uri:
            prefix: /
      route:
        - destination:
            host: {{ .Release.Name }}-{{ .Values.appFrontend.name }}
            subset: v1
          weight: 90
        - destination:
            host: {{ .Release.Name }}-{{ .Values.appFrontend.name }}
            subset: v2
          weight: 10
