apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ .Release.Name }}-{{ .Values.appFrontend.name }}-dr
spec:
  host: {{ .Release.Name }}-{{ .Values.appFrontend.name }}
  subsets:
    - name: v1
      labels:
        version: v1 
    - name: v2 
      labels:
        version: v2
  trafficPolicy:
    loadBalancer:
      consistentHash:
        httpHeaderName: user
