apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-{{ .Values.appFrontend.name }}-vs
spec:
  gateways:
    - {{ .Release.Name }}-gateway 
  hosts:
    - "*" 
  http:
    - name: "canary-group"
      match:
        - headers:
            user:
              regex: "^.{0,2}[0-1]"  # ~10% if last char 0 or 1 in first 3 chars
          uri:
            prefix: /
      route:
        - destination:
            host: {{ .Release.Name }}-{{ .Values.appFrontend.name }}
            subset: v2

    - name: "default-group"
      match:
        - uri:
            prefix: /
      route:
        - destination:
            host: {{ .Release.Name }}-{{ .Values.appFrontend.name }}
            subset: v1
