apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-{{ .Values.appFrontend.name }}-vs
spec:
  gateways:
    - {{ .Release.Name }}-gateway 
  hosts:
    - "*" 
  http:
    - name: "route-to-app-service"
      match:
        - uri:
            prefix: "/api/app-service/" 
      rewrite: 
        uri: "/"
      route:
        - destination:
            host: {{ .Release.Name }}-{{ .Values.appService.name }} 
            port:
              number: {{ .Values.appService.service.port }} 
    - name: "route-to-frontend" 
      match:
        - uri:
            prefix: / #
      route:
        - destination:
            host: {{ .Release.Name }}-{{ .Values.appFrontend.name }} 
            subset: v1
          weight: 90
        - destination:
            host: {{ .Release.Name }}-{{ .Values.appFrontend.name }} 
            subset: v2
          weight: 10