{
 "title": "Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Prediction Latency (50th Percentile) ",
   "type": "timeseries",
   "description": "Observe median latency to understand typical latency experience for users. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, rate(sentiment_prediction_latency_seconds_bucket[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Sentiment Predictions",
   "type": "timeseries",
   "description": "Tracks the total number of sentiment predictions made. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (sentiment) (sentiment_predictions_total)",
     "legendFormat": "{{`{{sentiment}}`}}"
    }
   ]
  },
  {
   "title": "Positive Sentiment Ratio",
   "type": "gauge",
   "description": "This gauge displays the proportion of all predictions that are classified as positive sentiment. A value of 0 means all recent predictions were negative, 1 means all were positive, and a value around 0.5 indicates a balanced mix.  ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sentiment_positive_ratio", "legendFormat": "__auto" }
   ]
  }
 ]
}