# Deployment for model-service v1 and v2
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Values.modelService.name }}
  labels:
    app: {{ .Release.Name }}-{{ .Values.modelService.name }}
spec:
  replicas: {{ .Values.modelService.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Values.modelService.name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Values.modelService.name }}
    spec:
      containers:
        - name: {{ .Values.modelService.name }}
          image: "{{ .Values.modelService.image.repository }}"
          imagePullPolicy: {{ .Values.modelService.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.modelService.service.port }}
              protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Values.modelService.name }}-v2
  labels:
    app: {{ .Release.Name }}-{{ .Values.modelService.name }}
    version: v2
spec:
  replicas: {{ .Values.modelService.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Values.modelService.name }}
      version: v2
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Values.modelService.name }}
        version: v2
    spec:
      containers:
        - name: {{ .Values.modelService.name }}-v2
          image: "{{ .Values.modelService.image.repository }}"
          imagePullPolicy: {{ .Values.modelService.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.modelService.service.port }}
              protocol: TCP
---
# Service for model-service
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.modelService.name }}
spec:
  selector:
    app: {{ .Release.Name }}-{{ .Values.modelService.name }}
  ports:
    - port: {{ .Values.modelService.service.port }}
      targetPort: {{ .Values.modelService.service.port }}
      protocol: TCP
  type: {{ .Values.modelService.service.type }}