apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-{{ .Values.modelService.name }}-vs
spec:
  hosts:
    - {{ .Release.Name }}-{{ .Values.modelService.name }}
  http:
    - name: "v1"
      match:
        - headers:
            app-version:
              exact: "v1"
      route:
        - destination:
            host: {{ .Release.Name }}-{{ .Values.modelService.name }}
            subset: v1

    - name: "v2"
      match:
        - headers:
            app-version:
              exact: "v2"
      route:
        - destination:
            host: {{ .Release.Name }}-{{ .Values.modelService.name }}
            subset: v2

    - name: "fallback"
      route:
        - destination:
            host: {{ .Release.Name }}-{{ .Values.modelService.name }}
            subset: v1
