apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ .Release.Name }}-{{ .Values.modelService.name }}-dr
spec:
  host: {{ .Release.Name }}-{{ .Values.modelService.name }}
  subsets:
    - name: v1
      labels:
        version: v1
    - name: v2
      labels:
        version: v2
  trafficPolicy:
    loadBalancer:
      consistentHash:
        httpHeaderName: user

