apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-{{ .Values.modelService.name }}-vs
spec:
  hosts:
    - {{ .Release.Name }}-{{ .Values.modelService.name }}
  http:
    - match:
        - sourceLabels:
            version: v2
      route:
        - destination:
            host: {{ .Release.Name }}-{{ .Values.modelService.name }}
            subset: v2
    - route:
        - destination:
            host: {{ .Release.Name }}-{{ .Values.modelService.name }}
            subset: v1
