# define deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Values.modelService.name }}
  labels:
    app: {{ .Release.Name }}-{{ .Values.modelService.name }}
spec:
  replicas: {{ .Values.modelService.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Values.modelService.name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Values.modelService.name }}
    spec:
      containers:
        - name: {{ .Values.modelService.name }}
          image: "{{ .Values.modelService.image.repository }}:{{ .Values.modelService.image.tag }}"
          imagePullPolicy: {{ .Values.modelService.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.modelService.service.port }}
              protocol: TCP
---
# define service
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.modelService.name }}
spec:
  selector:
    app: {{ .Release.Name }}-{{ .Values.modelService.name }}
  ports:
    - port: {{ .Values.modelService.service.port }}
      targetPort: {{ .Values.modelService.service.port }}
      protocol: TCP
  type: {{ .Values.modelService.service.type }}
