{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-app-secret
type: Opaque
stringData:
  {{- range $key, $value := .Values.secret.data }}
  {{ $key }}: "{{ $value }}"
  {{- end }}
  PASSWORD: "{{ $.Values.secret.data.smtpPassword }}"
{{- end }}
